---
title: "Fizyka 2"
author:
- Krzysztof Łopatowski
- Krzysztof Woźniak
- Aleksander Wiśniewski
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  pdf_document: default
  html_document:
    df_print: paged
  word_document: default
subtitle: Laboratorium 1
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(ggplot2)
library(knitr)
library(kableExtra)
```
   
# Wstęp

## Przedmiot badań

Laboratorium miało dwa przedmioty badań:

1. Przy użyciu **suwmiarki** i **mikrometru**, liczenie odpowiednich wielkości w przykładowym walcu i prostopadłościanie (szerokości, wysokości, średnice, głębokości).

2. Posiadając obwód elektryczny, odpowiednio podłączając zasilacz, **woltomierz** oraz **amperomierz**, liczenie zmieniających się napięć i natężeń prądu na opornikach.

## Cel badań

Głównym celem badań było sprawdzenie, czy zależność między napięciem a natężeniem prądu na oporniku jest zgodne z założeniem teoretycznym: $R=\frac{U}{I}$

# Teoria

Rozważane przez nas zagadnienie to prąd w obwodzie elektrycznym i zależność między spadkiem napięcia na oporniku a natężeniem prądu płynącego przez układ. Zależność nazwana **prawem Ohma** mówi, że stosunek napięcia do natężenia prądu jest stały: $\frac{U}{I}=const$. Stosunek ten nazywamy oporem elektrycznym: $R=\frac{U}{I}$.

Wartość oporu elektrycznego można też wyrazić w zależności od własności przewodnika: $R=\rho\frac{l}{S}$, gdzie $\rho$ to opór właściwy, $l$ to długość przewodu, a $S$ to pole przekroju.

Do pomiaru płynącego prądu stosuje się amperomierz, który podłącza się do obwodu szeregowo. Do zmierzenia spadku napięcia na oporniku wykorzystuje się woltomierz, który podłącza się równolegle. Amperomierz powinien charakteryzować się bardzo niskim oporem wewnętrznym, natomiast dla woltomierza powinno zachodzić $R_v\to\infty$

Istotnym zagadnieniem pierwszego laboratorium jest wyznaczanie niepewności pomiarowej: w kontekście obliczeń suwmiarką/mikrometrem, ale też w kontekście wyliczeń oporów. Wyróżniamy dwie metody obliczania niepewności pomiaru:

1. Obliczenie niepewności pomiaru **metodą typu A** jest metodą opartą o wyliczanie niepewności w oparciu o analizę statystyczną, np. przez metodę najmniejszych kwadratów

2. Obliczenie niepewności pomiaru **metodą typu B**: czyli każda metoda inna niż typu A. Zwykle w oparciu o dane o sprzęcie, np. niepewność wzorcowania, czy też niepewność eksperymentatora.

# Układ eksperymentalny

1. W pierwszej części laboratoriów używana była suwmiarka oraz mikrometr do badania różnych wielkości w prostpadłościanie i walcu. Dokładność suwmiarki wynosiła 0,02mm, a mikrometru: 0,01mm. W obu przypadkach niepewność eksperymentatora przyjęto jako połowę niepewności wzorcowania. \newline
W prostopadłościanie liczone były wszystkie wymiary. Długość i szerokość prostopadłościanu, rzędu kilku centymetrów, liczone były za pomocą suwmiarki. Wysokość prostopadłościanu liczona była za pomocą mikrometru.\newline
Walec charakteryzował się tym, że w jego środku wydrążona była dziura w kształcie walca. Ostatecznym celem było wyliczenie objętości większego walca, a w tym celu liczone były za pomocą suwmiarki: wysokość walca zewnętrznego, wysokość walca wewnętrznego, średnica walca wewnętrznego, średnica walca zewnętrznego. W celu wyliczenia objętości walca, odjęto objętość wewnętrznego od objętości walca zewnętrznego. Formuła na objętość walca to: $P=\pi r^2H$

2. Drugim celem laboratoriów były eksperymenty z obwodami elektrycznymi. Mieliśmy dostępną płytkę z obwodem, do której mogliśmy podłączać zasilanie, woltomierz oraz amperomierz. Używanym woltomierzem był miernik typu **UM-112B**. Do zliczania natężenia używano miernika **METEX M-3800**. Model zasilacza to **DF1730SL5A**. \newline
W ramach eksperymentu mierzone były napięcia i natężenia na czterech opornikach. Na trzech opornikach wykonano po jednym pomiarze, a na czwartym 10 pomiarów. Pomiary na czwartym oporniku wyglądały tak: na początku staraliśmy się ustawić zasilaczem natężenie prądu przepływającego przez opornik tak, aby amperomierz wskazywał 60mA. Sprawdzaliśmy wtedy spadek napięcia na oporniku na woltomierzu. W każdym kolejnym pomiarze staraliśmy się osiągać natężenie prądu o ~6mA mniejsze i ponownie sprawdzaliśmy napięcie.

# Dane eksperymentalne

## Prostopadłościan
### Wysokość

```{R, echo=FALSE}
pomiar_h <- read_excel("data.xlsx", "prost_h")


tabela_pomiar <- data.frame(pomiar_h["lp."],
                            pomiar_h["h"],
                            check.names = FALSE)

colnames(tabela_pomiar) <- c("lp.", "Wysokość ($mm$)")

kable(tabela_pomiar, format = "latex", escape = FALSE, align = 'c', caption = "Wysokość prostopadłościanu") %>%
   kable_styling(position = "center", latex_options = c("striped", "HOLD_position")) 
```

### Wymiary a, b
```{R, echo=FALSE}
pomiar_ab <- read_excel("data.xlsx", "prost_ab")


tabela_pomiar <- data.frame(pomiar_ab["lp."],
                            pomiar_ab["a"],
                            pomiar_ab["b"],
                            check.names = FALSE)

colnames(tabela_pomiar) <- c("lp.", "Bok a ($cm$)", "Bok b ($cm$)")

kable(tabela_pomiar, format = "latex", escape = FALSE, align = 'c', caption = "Boki a i b prostopadłościanu") %>%
   kable_styling(position = "center", latex_options = c("striped", "HOLD_position")) 
```

## Walec
### R, H, r

```{R, echo=FALSE}
pomiar_RHr <- read_excel("data.xlsx", "walec_RHr")


tabela_pomiar <- data.frame(pomiar_RHr["lp."],
                            pomiar_RHr["R"],
                            pomiar_RHr["H"],
                            pomiar_RHr["r"],
                            check.names = FALSE)

colnames(tabela_pomiar) <- c("lp.", "R ($cm$)", "H ($cm$)", "r ($cm$)")

kable(tabela_pomiar, format = "latex", escape = FALSE, align = 'c', caption = "Wymiary R, H i r walca") %>%
   kable_styling(position = "center", latex_options = c("striped", "HOLD_position")) 
```

### h

```{R, echo=FALSE}
pomiar_h <- read_excel("data.xlsx", "walec_h")


tabela_pomiar <- data.frame(pomiar_h["lp."],
                            pomiar_h["h"],
                            check.names = FALSE)

colnames(tabela_pomiar) <- c("lp.", "h ($cm$)")

kable(tabela_pomiar, format = "latex", escape = FALSE, align = 'c', caption = "Wysokość walca wewnętrzenego") %>%
   kable_styling(position = "center", latex_options = c("striped", "HOLD_position")) 
```

## Prądy

### R4

```{R, echo=FALSE}
pomiar_R4 <- read_excel("data.xlsx", "R4")


tabela_pomiar <- data.frame(pomiar_R4["lp."],
                            pomiar_R4["U"],
                            pomiar_R4["I"],
                            pomiar_R4["ZU"],
                            pomiar_R4["ZI"],
                            check.names = FALSE)

colnames(tabela_pomiar) <- c("lp.", "U ($V$)", "I ($mA$)", "Zakres U ($V$)", "Zakres I ($mA$)")

kable(tabela_pomiar, format = "latex", escape = FALSE, align = 'c', caption = "Wymiar h walca") %>%
   kable_styling(position = "center", latex_options = c("striped", "HOLD_position")) 
```

### R1, R2, R3

```{R, echo=FALSE}
pomiar_R123 <- read_excel("data.xlsx", "R123")


tabela_pomiar <- data.frame(pomiar_R123["lp."],
                            pomiar_R123["Opor"],
                            pomiar_R123["U"],
                            pomiar_R123["I"],
                            pomiar_R123["ZU"],
                            pomiar_R123["ZI"],
                            check.names = FALSE)

colnames(tabela_pomiar) <- c("lp.", "Opornik" ,"U ($V$)", "I ($mA$)", "Zakres U ($V$)", "Zakres I ($mA$)")

kable(tabela_pomiar, format = "latex", escape = FALSE, align = 'c', caption = "Oporniki R1, R2, R3") %>%
   kable_styling(position = "center", latex_options = c("striped", "HOLD_position")) 
```

